import Head from "next/head";
import styles from "@/styles/Home.module.css";
import axios from "axios";
import { isProductsList } from "@/src/utils/product";

export interface Product {
  id?: number;
  name: string;
  price: number;
  description: string;
}

export interface ProductsList {
  items: Array<Product>;
}

export interface HomeProps {
  products: ProductsList;
}

export default function Home(props: HomeProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1>Products</h1>
          {props.products.items.map((product) => (
            <div key={product.id} className={styles.productItem}>
              <h2>{product.name}</h2>
              <p>{product.description}</p>
              <b>Price: {product.price.toFixed(2)}</b>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const res = await axios("http://localhost:3000/api/products");
  let products: ProductsList;
  if (isProductsList(res.data)) {
    products = res.data as ProductsList;
  } else {
    products = { items: [] };
  }
  return {
    props: {
      products,
    },
  };
}
